# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: Update region prevalence

on:
  schedule:
    - cron: "* * * * *" # Every two days at 12:13 AM

jobs:
  generate-data:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - uses: r-lib/actions/setup-r@v2 # Set up R runtime
      
      - name: Install package dependencies
        run:
          Rscript -e "install.packages(c('tidyverse', 'ggthemes', 'data.table', 'gghighlight', 'zoo', 'scales'))"
          
      - name: Render plot
        run:
          Rscript -e "source('src/prevalence_region.R')"
          
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add plots/prevalence_by_region.png
          git commit -m 'Re-render prevalence_by_region.png'
          git push origin
      
                    
